plugins {
	id 'java'
}

group = 'ru.strelchm'
version = '0.0.1-SNAPSHOT'

subprojects {
    apply plugin: 'java'

    dependencies {
        // db
        runtimeOnly 'org.postgresql:postgresql'
        implementation 'com.zaxxer:HikariCP:7.1.0'

        // schedulers
        implementation 'com.github.kagkarlsson:db-scheduler:16.11.0'
        implementation 'org.jobrunr:jobrunr:8.8.2'

        // metrics
        implementation platform('io.micrometer:micrometer-bom:1.17.1')
        implementation 'io.micrometer:micrometer-registry-prometheus'

        // logging
        implementation 'org.slf4j:slf4j-api:2.0.17'

        // lombok
        compileOnly 'org.projectlombok:lombok:1.18.46'
        annotationProcessor 'org.projectlombok:lombok:1.18.46'
        testCompileOnly 'org.projectlombok:lombok:1.18.46'
        testAnnotationProcessor 'org.projectlombok:lombok:1.18.46'

        // testing
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}
