version: '3'
services:
  postgres-scheduler-perf:
    image: "postgres:15-alpine"
    container_name: postgres-scheduler-perf
    restart: always
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.max=10000
      - -c
      - pg_stat_statements.track=all
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "./docker/postgres/init:/docker-entrypoint-initdb.d:ro"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
#    ports:
#      - "6432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=schedulers

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres-exporter
    depends_on:
      postgres-scheduler-perf:
        condition: service_healthy
    ports:
      - "9187:9187"
    command:
      - --collector.stat_statements
    environment:
      - DATA_SOURCE_NAME=postgresql://myuser:mypassword@postgres-scheduler-perf:5432/schedulers?sslmode=disable
#      - PG_EXPORTER_EXTEND_QUERY_PATH=/etc/postgres_exporter/queries.yaml
    restart: always

  prometheus:
    image: prom/prometheus:latest
    user: "0"
    container_name: prometheus
    ports:
      - "9091:9090"
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./docker/prometheus/data:/prometheus

  grafana:
    image: grafana/grafana-oss:9.5.3
    container_name: grafana
    user: "0"
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    restart: always
    volumes:
      - ./docker/grafana/grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro

  scheduler-perf-app:
    build:
      context: ./
      dockerfile: ./spring-comparison/Dockerfile
    image: "scheduler-perf-app"
    container_name: scheduler-perf-app
    ports:
      - "8080:8080"
      - "8086:8085"
      - "8090:8090"
    depends_on:
      postgres-scheduler-perf:
        condition: service_healthy
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=db-scheduler #jobrunr,db-scheduler
