spring:
  application:
    name: scheduler-perf
  datasource:
    jdbc-url: jdbc:postgresql://localhost:6432/airdefence_auth
    username: airdefence
    password: airdefence
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

jobrunr:
  background-job-server:
    enabled: true
db-scheduler:
  enabled: false
