dependencies {
    // logging
    implementation 'ch.qos.logback:logback-classic:1.5.18'
    implementation 'org.slf4j:slf4j-simple:2.0.17'
}

//jar {
//    manifest {
//        attributes 'Main-Class': 'ru.strelchm.scheduler_perf.comparison.ComparisonApplication'
//    }
//    from {
//        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
//    }
//    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
//}
