spring:
  application:
    name: scheduler-perf
  datasource:
    jdbc-url: jdbc:postgresql://postgres-scheduler-perf:5432/schedulers
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 0

management:
  server:
    port: 8085
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      path-mapping:
        prometheus: /metrics
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

db-scheduler:
  enabled: false
jobrunr:
  background-job-server:
    enabled: false

mass:
  insert:
    enabled: true
    count: ${MASS_INSERT_COUNT:1000}
    sleepingJobsCount: ${MASS_INSERT_SLEEPING_COUNT}
    batch-size: ${MASS_INSERT_BATCH_SIZE:1000}
    delayMs: ${MASS_INSERT_DELAY_MS:0}
