spring:
  liquibase:
    change-log: classpath:/db/changelog/jobrunr/db.changelog-master.xml
    database-change-log-lock-table: jobrunr_change_log_lock
    database-change-log-table: jobrunr_change_log

jobrunr:
  background-job-server:
    poll-interval-in-seconds: ${POLL_INTERVAL_IN_SECONDS:5}
    worker-count: ${JOB_RUNR_WORKER_COUNT:10}
    enabled: true
    metrics:
      enabled: true
  jobs:
    metrics:
      enabled: true
    default-number-of-retries: 10
    retry-back-off-time-seed: 3

db-scheduler:
  enabled: false
