db-scheduler:
  enabled: true
  generic-lock-and-fetch: true
  polling-interval: ${POLL_INTERVAL_IN_SECONDS:5}s
  threads: ${DB_SCHEDULER_THREADS:10}
  polling-strategy: lock-and-fetch
  polling-strategy-lower-limit-fraction-of-threads: 0.1
  polling-strategy-upper-limit-fraction-of-threads: 1.0

jobrunr:
  background-job-server:
    enabled: false
