db.url=jdbc:postgresql://postgres-scheduler-perf:5432/schedulers
db.username=myuser
db.password=mypassword

scheduler.type=db-scheduler

mass.insert.enabled=true
mass.insert.count=1000
mass.insert.batch-size=1000
mass.insert.delayMs=0
